#!/bin/bash

#$ -M espaldin@nd.edu   # Email address for job notification
#$ -m abe            # Send mail when job begins, ends and aborts
#$ -pe smp 2     # Specify parallel environment and legal core size
#$ -q debug           # Specify queue
#$ -N rrlfe_test1       # Specify job name

### start timestamp
echo "Start time"
date

# set filesystem
export FILESYS = /afs/crc.nd.edu/user/e/espaldin/tmp/
export SING_FILE=lbti_altair_fizeau_latest.sif

# Required modules
module load python/3
module load singularity

singularity exec $FILESYS/$SING_FILE python high_level_application_script.py

# download PyPi package (SHOULD BE WITHIN SINGULARITY PACKAGE)
#pip install rrlfe

### mpirun -np $NSLOTS ./app # Application to execute

### timestamp end
echo "End time"
date
