#!/bin/bash

#$ -M espaldin@nd.edu   # Email address for job notification
#$ -m abe            # Send mail when job begins, ends and aborts
#$ -pe smp 8     # Specify parallel environment and legal core size
#$ -q debug           # Specify queue
#$ -N rrlfe_run_03       # Specify job name

### start timestamp
echo "Start time"
date

# set filesystem
export SING_PATH=/scratch365/espaldin/
export SING_FILE=test.sif
export CODE_HOME=/afs/crc.nd.edu/user/e/espaldin/Private/rrlfe_work

# Required modules
module load python/3

# remove stuff that was already there
rm -fr $CODE_HOME/rrlfe
rm -fr $CODE_HOME/robospect.py
rm -fr $CODE_HOME/requirements_bare_versions.txt

singularity run $SING_PATH/$SING_FILE
echo "Did run; now do exec"
# remove some input files if just want to test
#singularity exec $SING_PATH/$SING_FILE rm -v $CODE_HOME/rrlfe/src/model_spectra/rrmods_all/original_ascii_files/[5-6]*
singularity exec --bind $CODE_HOME/rrlfe:/Users/bandari/Documents/git.repos/rrlfe,$CODE_HOME/robospect.py:/Users/bandari/Documents/git.repos/robospect.py $SING_PATH/$SING_FILE python $CODE_HOME/rrlfe/high_level_reduction_script.py

### timestamp end
echo "End time"
date
